#cloud-config
autoinstall:
  version: 1
  locale: es_ES.UTF-8
  keyboard:
    layout: es
  timezone: Europe/Madrid

  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true

  identity:
    username: usuario
    hostname: usuarioubuntu
    password: 'D9E94FD2B4C5522E5BB7996AA4DF48A3F6B8F1B0C3E7FADB5FCC724E3AB6D85DC401B0A2789FE56C209B80E86102B218FF74FF8614F315599A180691846138B6'
