#cloud-config
autoinstall:
  version: 1

  source:
    id: ubuntu-server-minimal

  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true

  identity:
    username: usuario
    hostname: usuarioubuntu
    password: 'usuario'

  packages:
    - python3-pip
